### ISSUE TITLE
document: calculate_standard_deviation function

### ISSUE THREAD

**Issue by PANDASANG1231** [UBC-MDS/features_creator#36]

**Comment by NikitaShymberg** [comment]
Hey guys, I'm just writing the documentation for our package and I noticed that the calculate_standard_deviation function returns a dataframe whereas the other 2 functions return a numpy array. I don't really mind which method we choose but I think that we should stay consistent so that the documentation looks nice. @PANDASANG1231 could you change this function to return an np array?

**Comment by PANDASANG1231** [comment]
yeah, I plan to do that this week

**Comment by veerupandey** [comment]
@PANDASANG1231 If the usage section README and documentation (docs/example.ipynb) file looks good for this function, we can close this issue.

**Comment by PANDASANG1231** [comment]
sure
